### PR TITLE
Fixed error on SOLR Query

### PR DESCRIPTION
**Pull request by flutistar**
*Issue 20344, if available:*

*Description of changes:*
Got SOLR Query from SOLR UI and replaced with wrong one.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by EPortman** [comment]
What is the point of this?

SOLR queries are working in DEV? Just not in local. Why would changing DEV have an effect in local?

**Comment by flutistar** [comment]
> What is the point of this?
> 
> SOLR queries are working in DEV? Just not in local. Why would changing DEV have an effect in local?

I am sure SOLR queries are working in DEV.
I had a pairing session with Richard and SOLR query(with public URL) is working properly.

The only issue is we have wrong ENV variable in local.
@EPortman

**Comment by EPortman** [comment]
If the only issue is a wrong ENV variable in local. What is the point / effect of changing

'&fq=name_state_type_cd:A&fq=name_state_type_cd:R', 
TO
 '&fq=name_state_type_cd:(A%20OR%20R)',

**Comment by EPortman** [comment]
Like in DEV my SOLR is currently working
image

**Review by EPortman — APPROVED** [review]

**Pull request merged**
