### PR TITLE
11538 - Query for multiple nr_numbers

### PR DESCRIPTION
**Pull request by seeker25**
*Issue #, if available:* https://github.com/bcgov/entity/issues/11538

*Description of changes:*
Query for multiple nr_numbers

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Wasn't sure who to put on the review for this.

**Comment by argush3** [comment]
looks good.  Can we add a test for this?

**Review by vysakh-menon-aot — APPROVED** [review]

**Comment by seeker25** [comment]
This is been sitting for a while. I talked to Thor about this and he suggested we do it over queues instead?

**Comment by seeker25** [comment]
@pwei1018 Please take a look.

**Review by pwei1018 — APPROVED** [review]

**Pull request merged**
