### PR TITLE
Allow a name to be removed from nro name_instance table

### PR DESCRIPTION
**Pull request by perkinss**
*Issue #, if available:*
bcgov/entity#54

*Description of changes:*
Check whether new name is blank before adding a new row to the name_instance table in nro.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by katiemcgoff** [comment]
I believe there is an api change needed too - current code just blanks out name but doesn't remove the name record. The record needs to be removed from Namex db, otherwise it's considered a name to be actioned on - ie: if name 3 is "removed" (just blanked out), user can reject 1, reject 2, and now we're on name 3 trying to make a decision on a blank name. This is a bug.

**Comment by perkinss** [comment]
Oh! thanks for catching that
I'll look into it

**Comment by katiemcgoff** [comment]
Sorry, I see now that you posted the options for the UI for this, but I didn't see that note (among the many other ticket update emails). I don't think this solution is intuitive - disabling but no messaging. I think your first option would be better - validation error on choice 2. In which case, disabling choice 3 shouldn't necessarily be disabled, that's also confusing. Simple validation message, like choice 1, would be best I think. 

If you don't agree, let's give this to Scott to go through UX stuff.

**Comment by perkinss** [comment]
Working now

**Comment by perkinss** [comment]
Oh doh, this is on the wrong repo

**Comment by katiemcgoff** [comment]
There is one remaining issue, in postgres now, due to the changed behaviour. Closing this PR.

**Pull request merged**
