### PR TITLE
17185 Namex API / Auth API: Need new field for response of affiliated entities returned from BE

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #, if available:*
https://github.com/bcgov/entity/issues/17185

*Description of changes:*
add request_action_cd to requestRequestsAuthSearchSchema

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by severinbeauvais** [comment]
What will it take to get this PR approved and merged?

**Review by severinbeauvais — APPROVED** [review]
LGTM.

Have the linting and testing checks always failed?

**Comment by eve-git** [comment]
> LGTM.
> 
> Have the linting and testing checks always failed?

Yes, I tested in Postman. The changes work

**Comment by eve-git** [comment]
> LGTM.
> 
> Have the linting and testing checks always failed?

they always failed.

**Comment by eve-git** [comment]
> LGTM 🐱 But a small question, why is the naming convention different for these two fields?

not sure what happened. Maybe it coded by different developers.

**Comment by severinbeauvais** [comment]
@pwei1018 @thorwolpert @stevenc987 @mengdong19 @ozamani9gh @rarmitag

Could one of you, who are listed as code owners, please "bless" this PR so it can be merged? Thanks!

**Review by rarmitag — APPROVED** [review]

**Comment by severinbeauvais** [comment]
Ready to merge?

**Pull request merged**
