### PR TITLE
8554 fix transaction history for resubmit

### PR DESCRIPTION
**Pull request by vysakh-menon-aot**
*Issue:* bcgov/entity#8554

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]

**Review by argush3 — APPROVED** [review]

**Comment by andrepestana-aot** [comment]
Do we need this? I thought Severin would change RESUBMIT to NEW in the UI...

**Comment by severinbeauvais** [comment]
> Do we need this? I thought Severin would change RESUBMIT to NEW in the UI...

Yes, this change is for the PAYMENT (not the REQUEST).

**Comment by andrepestana-aot** [comment]
> > Do we need this? I thought Severin would change RESUBMIT to NEW in the UI...
> 
> Yes, this change is for the PAYMENT (not the REQUEST).

But as you're going to send NEW now we won't have any RESUBMIT anymore, right?

**Comment by severinbeauvais** [comment]
> But as you're going to send NEW now we won't have any RESUBMIT payment anymore, right? How can we identify it is a 'new' NR and the payment should RESUBMIT?

The payment is created separately from the NR.

**Comment by andrepestana-aot** [comment]
ok. So we're going to continue sending the request_action_cd as RESUBMIT to namex-api and namex-api needs to create a payment action as RESUBMIT? If so we'll need to change namex-api.

**Comment by severinbeauvais** [comment]
> ok. So we're going to continue sending the request_action_cd as RESUBMIT to namex-api and namex-api needs to create a payment action as RESUBMIT? If so we'll need to change namex-api.

When the user clicks the confirm button...
1. first the NR object is created, with action=NEW - see https://github.com/bcgov/namerequest/blob/18e008a779170b05784faf3c8b8b3236124b9aa2/src/components/dialogs/resubmit.vue#L208
2. then the payment object is created, with action=RESUBMIT - see https://github.com/bcgov/namerequest/blob/18e008a779170b05784faf3c8b8b3236124b9aa2/src/components/dialogs/resubmit.vue#L227

**Comment by andrepestana-aot** [comment]
ok. Yes. I think it's ok. Thanks!

**Comment by severinbeauvais** [comment]
Just to close this off:

Andre, I think I understand your concern: when I asked yesterday about the impact to use NEW instead of RESUBMIT action, you thought both the NR action and payment action would be changed -- but only the NR action has been changed. Preliminary testing shows that both NR and payment are working correctly. Riyaz will help with more testing.

Yes, I also think it's OK :)

**Pull request merged**
